#!/bin/sh
# build-apk.sh - Build UnEgg Alpine APK package
# Uses musl cross-compiler for static binary
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
PKG_DIR="$SCRIPT_DIR/packaging/alpine"
MUSL_TC="$PROJECT_DIR/.musl-toolchain"

echo "========================================="
echo "  UnEgg Alpine APK Package Builder"
echo "========================================="

# Step 1: Ensure musl toolchain
if [ ! -f "$MUSL_TC/bin/x86_64-linux-musl-g++" ]; then
    echo "[1/4] Downloading musl cross-compiler..."
    mkdir -p "$MUSL_TC"
    curl -sL https://musl.cc/x86_64-linux-musl-native.tgz | tar xz --strip-components=1 -C "$MUSL_TC"
else
    echo "[1/4] Musl toolchain found."
fi

# Step 2: Build static musl binary
echo "[2/4] Building static musl binary..."
cd "$PROJECT_DIR"
make clean
make -j$(nproc) \
    CXX="$MUSL_TC/bin/x86_64-linux-musl-g++" \
    CC="$MUSL_TC/bin/x86_64-linux-musl-gcc" \
    CXXFLAGS="-O2 -Wall -Wno-unused -Wno-multichar -std=c++11 -D_7ZIP_ST -D_GNU_SOURCE" \
    CFLAGS="-O2 -Wall -Wno-unused -Wno-multichar -D_7ZIP_ST -D_GNU_SOURCE" \
    LDFLAGS="-static"

echo "   Binary: $(ls -lh unegg | awk '{print $5}')"
echo "   Type: $(file unegg 2>/dev/null || echo 'statically linked')"

# Step 3: Stage package files
echo "[3/4] Staging package..."
APK_ROOT="$PKG_DIR/pkg/unegg"
rm -rf "$APK_ROOT"
mkdir -p "$APK_ROOT/usr/bin" "$APK_ROOT/usr/share/licenses/unegg"

install -m755 unegg "$APK_ROOT/usr/bin/unegg"
install -m644 Source/unegg/doc/license.txt "$APK_ROOT/usr/share/licenses/unegg/LICENSE"

# Generate checksums
cd "$APK_ROOT"
{
    echo "# checksum"
    find usr/ -type f -exec sha256sum {} \;
} > .sha256sums

# Generate .PKGINFO
SIZE=$(stat -c%s usr/bin/unegg)
BUILDDATE=$(date +%s)
cat > .PKGINFO << EOF
# Generated by build-apk.sh
pkgname = unegg
pkgver = 0.5-r0
pkgdesc = EGG/ALZ archive decompressor (ESTsoft format)
url = https://github.com/dterracino/UnEgg
builddate = $BUILDDATE
packager = OpenClaw <openclaw@example.com>
size = $SIZE
arch = x86_64
license = MIT
origin = unegg
provides = unegg
EOF

# Step 4: Create APK
echo "[4/4] Creating APK package..."
cd "$APK_ROOT"

# data.tar.gz
tar czf "$PKG_DIR/data.tar.gz" --exclude='.PKGINFO' --exclude='.sha256sums' --exclude='.SIGN*' usr/

# control.tar.gz
tar czf "$PKG_DIR/control.tar.gz" .PKGINFO .sha256sums

# Final APK
cd "$PKG_DIR"
APK_NAME="unegg-0.5-r0-x86_64.apk"
tar cf "$APK_NAME" control.tar.gz data.tar.gz

# Cleanup temp
rm -f control.tar.gz data.tar.gz

# Report
echo ""
echo "========================================="
echo "  BUILD COMPLETE"
echo "========================================="
ls -lh "$PKG_DIR/$APK_NAME"
echo ""
echo "Package contents:"
tar tf "$PKG_DIR/$APK_NAME"
echo ""
echo "To install on Alpine:"
echo "  apk add --allow-untrusted $APK_NAME"
echo ""
echo "To verify on Alpine:"
echo "  apk info -a unegg"
echo "  unegg -h"
